feat: implement initialMocks option for createGlobalLaikaLink
zendesk/laika pull request #33
Opened 2022-08-20 06:05 UTC by donovan-yohan

After finding need for a similar use-case to https://github.com/zendesk/laika/discussions/9 I decided to take a hand at implementing something simple that would allow for Laika to be used in situations where Apollo queries are made on page load.

In my specific use-case, having a client-level interceptor like Laika would help me conditionally use a mocked dataset without needing to do any extra work on the front-end components, and without needing to worry about the Apollo Server since the project I'm considering this for is using a federated graph.

I have a feeling this approach may be too naive as I haven't spent a lot of time with Laika yet, but I hope this can get the ball rolling and I'd love to hear any feedback or suggestions.

Thanks for the amazing work you've already done, and hope I can contribute to it!

2022-08-23 06:14 UTC, bbrzoska requested changes
Hey @donovan-yohan! Thanks for your contribution. 🙇 
The only thing I'm concerned about with this approach is that there's no way to access the interceptors instances that are created during the initial mocks.

What if instead of providing a list of `initialMocks`, there was an `onLaikaReady(laika)` callback that could be optionally passed into the `createGlobalLaikaLink` instead? This way the client could store the reference to the interpreters, plus have all the freedom as to the type of mocking that needed to be done.

If you wanna make that change, I'll be happy to merge it. If you have a better name than `onLaikaReady` (or maybe just `onReady`?), then feel free to propose it :) I'm not sure what name would work best.

2022-08-24 19:00 UTC, donovan-yohan commented
> Hey @donovan-yohan! Thanks for your contribution. 🙇 The only thing I'm concerned about with this approach is that there's no way to access the interceptor instances that are created during the initial mocks.
> 
> What if instead of providing a list of `initialMocks`, there was an `onLaikaReady(laika)` callback that could be optionally passed into the `createGlobalLaikaLink` instead? This way the client could store the reference to the interpreters, plus have all the freedom as to the type of mocking that needed to be done.
> 
> If you wanna make that change, I'll be happy to merge it. If you have a better name than `onLaikaReady` (or maybe just `onReady`?), then feel free to propose it :) I'm not sure what name would work best.

I think that makes a lot of sense, and simplifies the implementation on this end tremendously!

2022-08-26 20:06 UTC, bbrzoska approved these changes

2022-08-26 20:07 UTC, bbrzoska commented
Thanks @donovan-yohan!

2022-08-26 20:09 UTC, merged